apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-code-with-quarkus-wyne
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/e2e-demos-ijoo-tenant/quarkus/devfile-sample-code-with-quarkus-wyne@sha256:a12253ed1035c8d6ca7dca36bf9197022862762e9d8a3d9d1693754043f6f435
        name: my-java-quarkus
        resources: {}
status: {}
